ci: :construction_worker: Agregue un run para verificar si fallaron las pruebas

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -35,3 +35,10 @@ jobs:
 
     - name: Run tests
       run: npm run test:unit
+
+    - name: Check test status
+      run: |
+        if [ ${{ job.status }} != 'success' ]; then
+          echo "Tests failed. Exiting."
+          exit 1
+        fi
